# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
linters:
    enable:
        - tagalign
linters-settings:
    tagalign:
        align: true
        order: [json, yaml, hcl, cty]
        sort: true
        strict: true

issues:
    exclude-dirs:
        - "gen"
    exclude-files:
        - "\\s*.copy.\\s*"

    fix: true
