inpackage: false
with-expecter: true
testonly: false
exported: true
outpkg: mockery
resolve-type-alias: false
issue-845-fix: true
filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go"
mockname: Mock{{.InterfaceName}}_{{.PackageName}}
packages: #generated
