// Code generated by github.com/walteh/schema2go, DO NOT EDIT.

package test

// Root represents the root schema
type Root struct {
	// A user with both basic info and authentication details
	User User `json:"user"`
}

// Role represents the user role enum
type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
	UserRoleGuest UserRole = "guest"
)


type User struct {
	// Basic Info
	ID   int64   `json:"id"`           // Required
	Name *string `json:"name,omitempty"`
	Email string  `json:"email"`          // Required
	Role  *UserRole   `json:"role,omitempty"` // Optional role
} 