// Code generated by github.com/walteh/schema2go, DO NOT EDIT.

package test

// Root represents the root schema
type Root struct {
	// A user with both basic info and authentication details
	User User `json:"user"`
}

// Role represents the user role enum
type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
	RoleGuest Role = "guest"
)

// User represents a user with both basic info and authentication details
// This type is generated from an allOf combination of basic info and auth details
type User struct {
	// Basic Info
	ID   int64   `json:"id"`           // Required
	Name *string `json:"name,omitempty"`

	// Auth Details
	Email string  `json:"email"`          // Required
	Role  *Role   `json:"role,omitempty"` // Optional role
} 