// Code generated by github.com/walteh/schema2go, DO NOT EDIT.

package test

type Issue51 struct {
	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}
