// Code generated by github.com/walteh/schema2go, DO NOT EDIT.

package other

type Thing struct {
	// S corresponds to the JSON schema field "s".
	S *string `json:"s,omitempty" yaml:"s,omitempty" mapstructure:"s,omitempty"`
}
