// Code generated by statictypes.go; DO NOT EDIT.

package generator

var _ Schema = &StaticSchema{}

type StaticSchema struct {
	Package_ string
	Structs_ []Struct
	Enums_   []*EnumModel
	Imports_ []string
}

// Package implements Schema.
func (b *StaticSchema) Package() string {
	return b.Package_
}

// Structs implements Schema.
func (b *StaticSchema) Structs() []Struct {
	return b.Structs_
}

// Enums implements Schema.
func (b *StaticSchema) Enums() []*EnumModel {
	return b.Enums_
}

// Imports implements Schema.
func (b *StaticSchema) Imports() []string {
	return b.Imports_
}

var _ Struct = &StaticStruct{}

type StaticStruct struct {
	Name_                string
	Description_         string
	Fields_              []Field
	HasAllOf_            bool
	HasCustomMarshaling_ bool
	HasDefaults_         bool
	HasValidation_       bool
}

// Name implements Struct.
func (b *StaticStruct) Name() string {
	return b.Name_
}

// Description implements Struct.
func (b *StaticStruct) Description() string {
	return b.Description_
}

// Fields implements Struct.
func (b *StaticStruct) Fields() []Field {
	return b.Fields_
}

// HasAllOf implements Struct.
func (b *StaticStruct) HasAllOf() bool {
	return b.HasAllOf_
}

// HasCustomMarshaling implements Struct.
func (b *StaticStruct) HasCustomMarshaling() bool {
	return b.HasCustomMarshaling_
}

// HasDefaults implements Struct.
func (b *StaticStruct) HasDefaults() bool {
	return b.HasDefaults_
}

// HasValidation implements Struct.
func (b *StaticStruct) HasValidation() bool {
	return b.HasValidation_
}

var _ Field = &StaticField{}

type StaticField struct {
	Name_                string
	JSONName_            string
	Description_         string
	IsRequired_          bool
	Type_                string
	IsEnum_              bool
	EnumTypeName_        string
	EnumValues_          []*EnumValue
	DefaultValue_        *string
	DefaultValueComment_ *string
	ValidationRules_     []*ValidationRule
}

// Name implements Field.
func (b *StaticField) Name() string {
	return b.Name_
}

// JSONName implements Field.
func (b *StaticField) JSONName() string {
	return b.JSONName_
}

// Description implements Field.
func (b *StaticField) Description() string {
	return b.Description_
}

// IsRequired implements Field.
func (b *StaticField) IsRequired() bool {
	return b.IsRequired_
}

// Type implements Field.
func (b *StaticField) Type() string {
	return b.Type_
}

// IsEnum implements Field.
func (b *StaticField) IsEnum() bool {
	return b.IsEnum_
}

// EnumTypeName implements Field.
func (b *StaticField) EnumTypeName() string {
	return b.EnumTypeName_
}

// EnumValues implements Field.
func (b *StaticField) EnumValues() []*EnumValue {
	return b.EnumValues_
}

// DefaultValue implements Field.
func (b *StaticField) DefaultValue() *string {
	return b.DefaultValue_
}

// DefaultValueComment implements Field.
func (b *StaticField) DefaultValueComment() *string {
	return b.DefaultValueComment_
}

// ValidationRules implements Field.
func (b *StaticField) ValidationRules() []*ValidationRule {
	return b.ValidationRules_
}

func NewStaticSchema(impl Schema) *StaticSchema {
	return &StaticSchema{
		Package_: impl.Package(),
		Structs_: impl.Structs(),
		Enums_:   impl.Enums(),
		Imports_: impl.Imports(),
	}
}

func NewStaticStruct(impl Struct) *StaticStruct {
	return &StaticStruct{
		Name_:                impl.Name(),
		Description_:         impl.Description(),
		Fields_:              impl.Fields(),
		HasAllOf_:            impl.HasAllOf(),
		HasCustomMarshaling_: impl.HasCustomMarshaling(),
		HasDefaults_:         impl.HasDefaults(),
		HasValidation_:       impl.HasValidation(),
	}
}

func NewStaticField(impl Field) *StaticField {
	return &StaticField{
		Name_:                impl.Name(),
		JSONName_:            impl.JSONName(),
		Description_:         impl.Description(),
		IsRequired_:          impl.IsRequired(),
		Type_:                impl.Type(),
		IsEnum_:              impl.IsEnum(),
		EnumTypeName_:        impl.EnumTypeName(),
		EnumValues_:          impl.EnumValues(),
		DefaultValue_:        impl.DefaultValue(),
		DefaultValueComment_: impl.DefaultValueComment(),
		ValidationRules_:     impl.ValidationRules(),
	}
}
